sudo: false
language: python

python:
  - "2.7"
  - "2.6"
  - "3.3"
  - "3.4"
  - "3.5"

cache:
  directories:
  - ${HOME}/.cache
script:
  - pip install tox
  - tox -e flake8
  - if [[ ${TRAVIS_PYTHON_VERSION%py} != ${TRAVIS_PYTHON_VERSION} ]]; then export TOXENV=${TRAVIS_PYTHON_VERSION}; else TOXENV=py"${TRAVIS_PYTHON_VERSION/./}"; fi
  - tox -e $TOXENV
notifications:
  email: false

